### ISSUE TITLE
Biroamer fails when extra corpus is provided

### ISSUE THREAD

**Issue by cgr71ii** [bitextor/biroamer#3]
When extra corpus is provided in order to improve alignment, Biroamer fails due to recent commit where strict mode has been enabled in `biroamer.sh`. The problem is that when extra corpus is provided, `head` is used in `biroamer.sh`, and a concrete nolines is set. If this nolines is less than the nolines of the `paste` command, the exit code is 141 as explained in https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q.

The line which fails is: https://github.com/bitextor/biroamer/blob/37139ed9e8bcd48964502130d924a79d276ee884/biroamer.sh#L124

The corpus which I'm using is of 500 lines (the `head` command attempts to retrieve 2996 lines), and I know that the minimum recommended is 100k, but I think that should not fail anyway.

**Comment by ZJaume** [comment]
I'm not being able to reproduce this error, please, could you tell me the exact amount of lines for the input and the extra aligment corpus?

**Comment by ZJaume** [comment]
Never mind! I thought that biroamer was failing before writing the output. So, the problem here is that the script is returning non-zero exit code because `head` in a pipe using `set -o pipefail` causes this. That means that the pipe should be divided in two parts and write partial results on disk, I guess.

**Comment by ZJaume** [comment]
It seems that `tail` does not cause `SIGPIPE`, clone https://github.com/bitextor/biroamer/commit/5cbd4f61fae52dc0d53f8f7291b6cb30c3a31ce0 to see if it works for you.

**Comment by cgr71ii** [comment]
Yes, now it seems to work perfectly!
