### ISSUE TITLE
E-mail addresses and phone numbers

### ISSUE THREAD

**Issue by kpu** [bitextor/biroamer#4]
Should you also remove e-mail addresses and phone numbers?
```
        <seg>Pour obtenir plus d’informations sur la location de la bastide, merci de me contacter par mail bastidelebosquet@gmail.com ou par téléphone 0033(0)651767273.</seg>
```
from `zcat en-fr.roam.tmx.gz |fgrep "0033("`

I see there is code for this: https://github.com/bitextor/biroamer/blob/ad20c8b097c2a5a234943fe63d2cfc018dd85e3f/biner.py#L13-L15 but not sure why it didn't match a simple gmail.com address.

**Comment by ZJaume** [comment]
This particular case comes from a sentence pair that does not contain those entities on the source language:
```
For more information on the rental of the Bastide, please to contact me. Access & Location La Bastide du Bosquet is ideally located in the heart of the Côte d’Azur.    Pour obtenir plus d’informations sur la location de la bastide, merci de me contacter par mail bastidelebosquet@gmail.com ou par téléphone 0033(0)651767273.   0.540
```

This is because we are only detecting entities on the source and then align the entity tags to the target. It could be mitigated doing an extra step wiht the regex on the target if there are no identified entities on the source.

**Comment by ZJaume** [comment]
BTW I've checked the email and the phone number and both are correctly parsed by the biner regex.

**Comment by kpu** [comment]
Ok, I get why we are doing named entities on the en side.  Regex we should do on the non-en side too.

**Comment by ZJaume** [comment]
Fixed with https://github.com/bitextor/biroamer/commit/bc06aa4908856bf5bd49b81c55704cf711d72639

```xml
    <tu>
      <tuv xml:lang="en">
        <seg>For more information on the rental of the Bastide, please to contact me. Access Location La Bastide du Bosquet is ideally located in the heart of the Côte d’Azur.</seg>
      </tuv>
      <tuv xml:lang="es">
        <seg>Pour obtenir plus d’informations sur la location de la bastide, merci de me contacter par mail <hi>bastidelebosquet@gmail.com</hi> ou par téléphone <hi>0033(0)651767273</hi>.</seg>
      </tuv>
    </tu>
 ```
